In [ ]:
import pandas as pd
df = pd.read_csv("Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1, inplace = True)

In [ ]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
y = df['Exited'].values
x = df.loc[:, df.columns != 'Exited'].values

In [ ]:
#Encoding and Normalizing Columns Gender and Geography
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

encoder = LabelEncoder()
x[:, 1] = encoder.fit(x[:, 1])
x[:, 2] = encoder.fit(x[:, 2])

pipeline = Pipeline(
    [
        ('Categorizer', ColumnTransformer(
            [
                ("Gender Label Encoder", OneHotEncoder(categories="auto", drop="first"), [2]),
                ("Geography Label Encoder", OneHotEncoder(categories="auto", drop="first"), [1])
            ],
            remainder="passthrough", n_jobs = 1)),
        ('Normalizer', StandardScaler())
    ]
)

In [ ]:
x = pipeline.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418,  0.29351742,  1.03290776, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -1.04143285, -0.35020386, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [ ]:
#Splitting data
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.33)

In [ ]:
#Neural Network
#Creation
from keras.models import Sequential
from keras.layers import Dense, Dropout

classifier = Sequential() #Initialization

In [ ]:
classifier.add(Dense(6, activation = 'relu', input_shape = (X_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
classifier.add(Dense(6, activation = "relu"))
classifier.add(Dropout(rate = 0.1))

In [ ]:
classifier.add(Dense(1, activation = "sigmoid"))

In [ ]:
classifier.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 6)                   │              54 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 6)                   │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_6 (Dropout)                  │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 1)                   │               7 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 103 (412.00 B)

 Trainable params: 103 (412.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Optimize the weights
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Fitting the NN
history = classifier.fit(X_train, Y_train, batch_size = 32, epochs = 50, validation_split = 0.1, verbose = 2)

Epoch 1/50
189/189 - 2s - 13ms/step - accuracy: 0.6028 - loss: 0.6739 - val_accuracy: 0.8119 - val_loss: 0.5391
Epoch 2/50
189/189 - 1s - 5ms/step - accuracy: 0.7950 - loss: 0.5258 - val_accuracy: 0.8119 - val_loss: 0.4852
Epoch 3/50
189/189 - 1s - 3ms/step - accuracy: 0.7955 - loss: 0.4904 - val_accuracy: 0.8149 - val_loss: 0.4687
Epoch 4/50
189/189 - 1s - 4ms/step - accuracy: 0.7973 - loss: 0.4712 - val_accuracy: 0.8209 - val_loss: 0.4620
Epoch 5/50
189/189 - 1s - 4ms/step - accuracy: 0.7988 - loss: 0.4661 - val_accuracy: 0.8254 - val_loss: 0.4568
Epoch 6/50
189/189 - 1s - 3ms/step - accuracy: 0.8051 - loss: 0.4599 - val_accuracy: 0.8239 - val_loss: 0.4527
Epoch 7/50
189/189 - 1s - 3ms/step - accuracy: 0.8007 - loss: 0.4550 - val_accuracy: 0.8284 - val_loss: 0.4490
Epoch 8/50
189/189 - 1s - 3ms/step - accuracy: 0.8022 - loss: 0.4495 - val_accuracy: 0.8269 - val_loss: 0.4470
Epoch 9/50
189/189 - 0s - 2ms/step - accuracy: 0.8090 - loss: 0.4467 - val_accuracy: 0.8284 - val_loss: 0.4435
Epoch 10/50
189/189 - 1s - 3ms/step - accuracy: 0.8113 - loss: 0.4440 - val_accuracy: 0.8313 - val_loss: 0.4412
Epoch 11/50
189/189 - 0s - 2ms/step - accuracy: 0.8113 - loss: 0.4398 - val_accuracy: 0.8343 - val_loss: 0.4388
Epoch 12/50
189/189 - 0s - 2ms/step - accuracy: 0.8166 - loss: 0.4364 - val_accuracy: 0.8358 - val_loss: 0.4348
Epoch 13/50
189/189 - 1s - 3ms/step - accuracy: 0.8192 - loss: 0.4326 - val_accuracy: 0.8343 - val_loss: 0.4323
Epoch 14/50
189/189 - 1s - 3ms/step - accuracy: 0.8184 - loss: 0.4376 - val_accuracy: 0.8358 - val_loss: 0.4302
Epoch 15/50
189/189 - 1s - 3ms/step - accuracy: 0.8207 - loss: 0.4340 - val_accuracy: 0.8328 - val_loss: 0.4279
Epoch 16/50
189/189 - 1s - 3ms/step - accuracy: 0.8245 - loss: 0.4285 - val_accuracy: 0.8358 - val_loss: 0.4255
Epoch 17/50
189/189 - 1s - 3ms/step - accuracy: 0.8224 - loss: 0.4312 - val_accuracy: 0.8403 - val_loss: 0.4233
Epoch 18/50
189/189 - 1s - 3ms/step - accuracy: 0.8229 - loss: 0.4313 - val_accuracy: 0.8448 - val_loss: 0.4225
Epoch 19/50
189/189 - 1s - 3ms/step - accuracy: 0.8231 - loss: 0.4251 - val_accuracy: 0.8403 - val_loss: 0.4208
Epoch 20/50
189/189 - 0s - 2ms/step - accuracy: 0.8231 - loss: 0.4243 - val_accuracy: 0.8448 - val_loss: 0.4203
Epoch 21/50
189/189 - 1s - 4ms/step - accuracy: 0.8239 - loss: 0.4286 - val_accuracy: 0.8478 - val_loss: 0.4187
Epoch 22/50
189/189 - 0s - 2ms/step - accuracy: 0.8242 - loss: 0.4293 - val_accuracy: 0.8433 - val_loss: 0.4187
Epoch 23/50
189/189 - 0s - 2ms/step - accuracy: 0.8292 - loss: 0.4224 - val_accuracy: 0.8463 - val_loss: 0.4197
Epoch 24/50
189/189 - 0s - 2ms/step - accuracy: 0.8240 - loss: 0.4280 - val_accuracy: 0.8463 - val_loss: 0.4173
Epoch 25/50
189/189 - 1s - 3ms/step - accuracy: 0.8272 - loss: 0.4236 - val_accuracy: 0.8463 - val_loss: 0.4168
Epoch 26/50
189/189 - 1s - 3ms/step - accuracy: 0.8287 - loss: 0.4215 - val_accuracy: 0.8463 - val_loss: 0.4172
Epoch 27/50
189/189 - 0s - 2ms/step - accuracy: 0.8307 - loss: 0.4220 - val_accuracy: 0.8463 - val_loss: 0.4168
Epoch 28/50
189/189 - 1s - 3ms/step - accuracy: 0.8287 - loss: 0.4243 - val_accuracy: 0.8433 - val_loss: 0.4167
Epoch 29/50
189/189 - 1s - 3ms/step - accuracy: 0.8289 - loss: 0.4227 - val_accuracy: 0.8448 - val_loss: 0.4166
Epoch 30/50
189/189 - 1s - 3ms/step - accuracy: 0.8289 - loss: 0.4242 - val_accuracy: 0.8418 - val_loss: 0.4151
Epoch 31/50
189/189 - 1s - 3ms/step - accuracy: 0.8265 - loss: 0.4224 - val_accuracy: 0.8433 - val_loss: 0.4155
Epoch 32/50
189/189 - 1s - 3ms/step - accuracy: 0.8308 - loss: 0.4182 - val_accuracy: 0.8418 - val_loss: 0.4152
Epoch 33/50
189/189 - 1s - 3ms/step - accuracy: 0.8292 - loss: 0.4191 - val_accuracy: 0.8418 - val_loss: 0.4151
Epoch 34/50
189/189 - 1s - 3ms/step - accuracy: 0.8252 - loss: 0.4243 - val_accuracy: 0.8418 - val_loss: 0.4163
Epoch 35/50
189/189 - 1s - 3ms/step - accuracy: 0.8264 - loss: 0.4233 - val_accuracy: 0.8448 - val_loss: 0.4165
Epoch 36/50
189/189 - 1s - 3ms/step - accuracy: 0.8270 - loss: 0.4219 - val_accuracy: 0.8448 - val_loss: 0.4171
Epoch 37/50
189/189 - 1s - 3ms/step - accuracy: 0.8302 - loss: 0.4200 - val_accuracy: 0.8448 - val_loss: 0.4156
Epoch 38/50
189/189 - 1s - 3ms/step - accuracy: 0.8262 - loss: 0.4196 - val_accuracy: 0.8418 - val_loss: 0.4159
Epoch 39/50
189/189 - 1s - 4ms/step - accuracy: 0.8284 - loss: 0.4215 - val_accuracy: 0.8418 - val_loss: 0.4179
Epoch 40/50
189/189 - 0s - 2ms/step - accuracy: 0.8272 - loss: 0.4197 - val_accuracy: 0.8418 - val_loss: 0.4159
Epoch 41/50
189/189 - 1s - 3ms/step - accuracy: 0.8272 - loss: 0.4224 - val_accuracy: 0.8418 - val_loss: 0.4170
Epoch 42/50
189/189 - 1s - 3ms/step - accuracy: 0.8279 - loss: 0.4231 - val_accuracy: 0.8418 - val_loss: 0.4172
Epoch 43/50
189/189 - 1s - 3ms/step - accuracy: 0.8274 - loss: 0.4209 - val_accuracy: 0.8418 - val_loss: 0.4179
Epoch 44/50
189/189 - 1s - 3ms/step - accuracy: 0.8308 - loss: 0.4190 - val_accuracy: 0.8433 - val_loss: 0.4167
Epoch 45/50
189/189 - 0s - 2ms/step - accuracy: 0.8270 - loss: 0.4225 - val_accuracy: 0.8433 - val_loss: 0.4160
Epoch 46/50
189/189 - 0s - 2ms/step - accuracy: 0.8289 - loss: 0.4176 - val_accuracy: 0.8403 - val_loss: 0.4168
Epoch 47/50
189/189 - 0s - 2ms/step - accuracy: 0.8277 - loss: 0.4203 - val_accuracy: 0.8448 - val_loss: 0.4153
Epoch 48/50
189/189 - 1s - 3ms/step - accuracy: 0.8289 - loss: 0.4206 - val_accuracy: 0.8448 - val_loss: 0.4155
Epoch 49/50
189/189 - 1s - 3ms/step - accuracy: 0.8279 - loss: 0.4192 - val_accuracy: 0.8448 - val_loss: 0.4148
Epoch 50/50
189/189 - 0s - 2ms/step - accuracy: 0.8267 - loss: 0.4252 - val_accuracy: 0.8448 - val_loss: 0.4158

In [ ]:
prediction = classifier.predict(X_test)

104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
prediction = (prediction>0.5).astype(int)

In [ ]:
from sklearn import metrics
cm = metrics.confusion_matrix(Y_test, prediction)
print(cm)

[[2537   77]
 [ 496  190]]

In [ ]:
print(metrics.accuracy_score(Y_test, prediction))

0.8263636363636364

In [ ]:

print(((cm[0][0] + cm[1][1])* 100) / len(Y_test), '% of data was classified correctly')

82.63636363636364 % of data was classified correctly

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar = False,
            xticklabels=["Positive", "Negative"],
            yticklabels=["Positive", "Negative"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()